version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: roots123
      POSTGRES_DB: my-stonks-api-db
    ports:
      - "5432:5432"
    volumes:
      - stonks_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db_test:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: roots123
      POSTGRES_DB: my-stonks-api-db-test
    ports:
      - "5434:5432"
    volumes:
      - stonks_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:5540"
    depends_on:
      - redis

volumes:
  stonks_data:
  redis_data:
  stonks_test_data: